#!/usr/bin/env python3
"""Shared helpers for the Kirpich asm parsers.

Extracted when the second parser (parse_charmap.py) landed: the structural-assert error type, the
generated-file banner, C++ string escaping, and the upstream-commit probe are identical across
parsers, so they live here rather than being copied. Scope is exactly what the shipped parsers
use - no speculative surface.

Python 3 stdlib only. Port-time tooling - never a build-time or CI dependency.
"""

from __future__ import annotations

import subprocess
from pathlib import Path


class ParseError(SystemExit):
    """A structural assertion failed. Carries a source citation; halts the emit run.

    Each parser subclasses this and overrides `script` so the message is prefixed with the emitting
    parser's name (`parse_core_enums: STRUCTURAL ASSERT FAILED ...`).
    """

    script = "asm_parser"

    def __init__(self, message: str) -> None:
        super().__init__(f"{self.script}: STRUCTURAL ASSERT FAILED\n  {message}")


def banner(script_name: str, source_commit: str) -> str:
    """The three-line 'do not hand-edit' banner atop every emitted artifact."""
    return (
        f"// GENERATED by tools/asm_parser/{script_name} - do not hand-edit.\n"
        f"// Transcribed from the kaspermeerts/tetris disassembly (upstream @ {source_commit}).\n"
        "// Regenerate with `--all` after any upstream repin; edits here are overwritten.\n"
    )


def cpp_escape(text: str) -> str:
    """Escape a string for a C++ double-quoted literal: backslash first, then the double quote."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def source_commit_of(source_root: Path) -> str:
    """Short git commit of the disassembly checkout, or 'unknown' when git or the checkout is absent."""
    try:
        out = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip() or "unknown"
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return "unknown"
