#!/usr/bin/env python3
"""Unit tests for tools/asm_parser/common.py (helpers shared across the asm parsers).

Python 3 stdlib only. Run from the project root:
  python3 -m unittest tools.asm_parser.test_parse_common
Or on CI:
  python3 -m unittest discover -s tools/asm_parser -p 'test_parse_*.py'
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

# Importable whether run via the package path or via `discover -s tools/asm_parser`.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402


class CppEscape(unittest.TestCase):
    def test_plain_unchanged(self):
        self.assertEqual(common.cpp_escape("pause"), "pause")

    def test_empty(self):
        self.assertEqual(common.cpp_escape(""), "")

    def test_double_quote_escaped(self):
        self.assertEqual(common.cpp_escape('a"b'), 'a\\"b')

    def test_backslash_escaped(self):
        self.assertEqual(common.cpp_escape("a\\b"), "a\\\\b")

    def test_backslash_then_quote_order(self):
        # Backslash is escaped first, so the input `\"` becomes `\\\"`, never `\\"`.
        self.assertEqual(common.cpp_escape('\\"'), '\\\\\\"')


class Banner(unittest.TestCase):
    def test_three_lines(self):
        self.assertEqual(common.banner("parse_x.py", "abc1234").count("\n"), 3)

    def test_contains_script_and_commit(self):
        text = common.banner("parse_x.py", "abc1234")
        self.assertIn("tools/asm_parser/parse_x.py", text)
        self.assertIn("abc1234", text)
        self.assertIn("do not hand-edit", text)

    def test_reproduces_core_enums_legacy_first_line(self):
        # Byte-identity guard: the extracted banner must reproduce the pre-extraction first line
        # exactly, or the parse_core_enums refactor would silently rewrite its emitted headers.
        text = common.banner("parse_core_enums.py", "deadbee")
        self.assertTrue(text.startswith(
            "// GENERATED by tools/asm_parser/parse_core_enums.py - do not hand-edit.\n"
        ))


class SourceCommitOf(unittest.TestCase):
    def test_non_repo_returns_unknown(self):
        with tempfile.TemporaryDirectory() as tmp:
            self.assertEqual(common.source_commit_of(Path(tmp)), "unknown")


class ParseErrorPrefix(unittest.TestCase):
    def test_is_system_exit(self):
        self.assertTrue(issubclass(common.ParseError, SystemExit))

    def test_default_script_prefix(self):
        with self.assertRaises(SystemExit) as ctx:
            raise common.ParseError("something drifted")
        self.assertIn("asm_parser: STRUCTURAL ASSERT FAILED", str(ctx.exception))
        self.assertIn("something drifted", str(ctx.exception))

    def test_subclass_overrides_script(self):
        class ParseError(common.ParseError):
            script = "parse_demo"

        with self.assertRaises(SystemExit) as ctx:
            raise ParseError("bad line")
        self.assertIn("parse_demo: STRUCTURAL ASSERT FAILED", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
