#pragma once
// GENERATED by tools/asm_parser/parse_charmap.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// CharTile - a text glyph's VRAM tile index, named. The character map (charmap.asm) is the ROM's
// naming table for the text glyph space: every sequence it maps names the glyph at its tile index,
// and those names are minted here as enumerators, byte values preserved. The tile sheet holds
// further glyphs the charmap never names (used directly by tilemaps and code); enumerators for
// those are added as the surfaces that use them land, so this enum grows with the port.

#include <cstdint>

namespace kirpich {

enum class CharTile : std::uint8_t {
    DIGIT_0                   = 0x00,  // "0"
    DIGIT_1                   = 0x01,  // "1"
    DIGIT_2                   = 0x02,  // "2"
    DIGIT_3                   = 0x03,  // "3"
    DIGIT_4                   = 0x04,  // "4"
    DIGIT_5                   = 0x05,  // "5"
    DIGIT_6                   = 0x06,  // "6"
    DIGIT_7                   = 0x07,  // "7"
    DIGIT_8                   = 0x08,  // "8"
    DIGIT_9                   = 0x09,  // "9"
    LETTER_A                  = 0x0A,  // "a"
    LETTER_B                  = 0x0B,  // "b"
    LETTER_C                  = 0x0C,  // "c"
    LETTER_D                  = 0x0D,  // "d"
    LETTER_E                  = 0x0E,  // "e"
    LETTER_F                  = 0x0F,  // "f"
    LETTER_G                  = 0x10,  // "g"
    LETTER_H                  = 0x11,  // "h"
    LETTER_I                  = 0x12,  // "i"
    LETTER_J                  = 0x13,  // "j"
    LETTER_K                  = 0x14,  // "k"
    LETTER_L                  = 0x15,  // "l"
    LETTER_M                  = 0x16,  // "m"
    LETTER_N                  = 0x17,  // "n"
    LETTER_O                  = 0x18,  // "o"
    LETTER_P                  = 0x19,  // "p"
    LETTER_Q                  = 0x1A,  // "q"
    LETTER_R                  = 0x1B,  // "r"
    LETTER_S                  = 0x1C,  // "s"
    LETTER_T                  = 0x1D,  // "t"
    LETTER_U                  = 0x1E,  // "u"
    LETTER_V                  = 0x1F,  // "v"
    LETTER_W                  = 0x20,  // "w"
    LETTER_X                  = 0x21,  // "x"
    LETTER_Y                  = 0x22,  // "y"
    LETTER_Z                  = 0x23,  // "z"
    PERIOD                    = 0x24,  // "."
    HYPHEN                    = 0x25,  // "-"
    MULTIPLICATION_SIGN       = 0x26,  // "<U+00D7>"
    HEART                     = 0x27,  // "<U+2665>"
    MIDLINE_ELLIPSIS          = 0x29,  // "<U+22EF>"
    SPACE                     = 0x2F,  // " "
    COPYRIGHT                 = 0x33,  // "<U+00A9>"
    ELLIPSIS                  = 0x60,  // "<U+2026>"
    RIGHT_DOUBLE_QUOTE        = 0x9B,  // "<U+201D>"
    COMMA                     = 0x9C,  // ","
    PERIOD_RIGHT_DOUBLE_QUOTE = 0x9D,  // ".<U+201D>"
};

}  // namespace kirpich
