#pragma once
// GENERATED by tools/asm_parser/parse_core_enums.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.

#include <cstdint>

namespace kirpich {

// Which side of the two-player link cable this Game Boy is. Elected during the serial handshake:
// a Game Boy that reads the SLAVE code back from the wire becomes the MASTER, and vice versa.
enum class SerialRole : uint8_t {
    MASTER = 0x29,
    SLAVE  = 0x55,
};

}  // namespace kirpich
