#pragma once
// GENERATED by tools/asm_parser/parse_core_enums.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.

#include <cstdint>

namespace kirpich {

// The serial-control clock source written to rSC when starting a transfer. EXTERNAL waits for the
// other Game Boy to drive the clock (this side is the slave); INTERNAL drives it (this side is the
// master).
enum class SerialClockMode : uint8_t {
    EXTERNAL = 0x80,
    INTERNAL = 0x81,
};

}  // namespace kirpich
