#pragma once
// GENERATED by tools/asm_parser/parse_sprites.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// The 94 composed OAM sprites the game can draw, in SpriteList index order. The value is the index
// the game passes in a sprite descriptor (and the score screen passes to pick a rocket ending); it
// is a dense identity space, 0x00..0x5D, with no "none" value - visibility is a separate descriptor
// byte. Four identities alias an earlier target's layout (the _ALT enumerators); they are distinct
// ids with equal composed geometry. The composition each id resolves to lives in src/data/sprites.h;
// the layout and the renderer's walk are specified in docs/contracts/sprites.md.

#include <cstdint>

namespace kirpich {

enum class SpriteId : std::uint8_t {
    // Falling-piece rotation sprites - four per tetromino, in PieceKind order (L, J, I, O, S, Z, T).
    L_0 = 0x00,
    L_1 = 0x01,
    L_2 = 0x02,
    L_3 = 0x03,
    J_0 = 0x04,
    J_1 = 0x05,
    J_2 = 0x06,
    J_3 = 0x07,
    I_0 = 0x08,
    I_1 = 0x09,
    I_2 = 0x0A,
    I_3 = 0x0B,
    O_0 = 0x0C,
    O_1 = 0x0D,
    O_2 = 0x0E,
    O_3 = 0x0F,
    S_0 = 0x10,
    S_1 = 0x11,
    S_2 = 0x12,
    S_3 = 0x13,
    Z_0 = 0x14,
    Z_1 = 0x15,
    Z_2 = 0x16,
    Z_3 = 0x17,
    T_0 = 0x18,
    T_1 = 0x19,
    T_2 = 0x1A,
    T_3 = 0x1B,

    // Game-type labels and the music-off label.
    A_TYPE = 0x1C,
    B_TYPE = 0x1D,
    C_TYPE = 0x1E,
    OFF = 0x1F,

    // Score digits 0-9.
    DIGIT_0 = 0x20,
    DIGIT_1 = 0x21,
    DIGIT_2 = 0x22,
    DIGIT_3 = 0x23,
    DIGIT_4 = 0x24,
    DIGIT_5 = 0x25,
    DIGIT_6 = 0x26,
    DIGIT_7 = 0x27,
    DIGIT_8 = 0x28,
    DIGIT_9 = 0x29,

    // Victory-and-defeat characters, the Buran shuttle, and their smoke and exhaust.
    JUMPING_LARGE_MARIO_1 = 0x2A,
    JUMPING_LARGE_MARIO_2 = 0x2B,
    BURAN = 0x2C,
    JUMPING_LARGE_MARIO_2_ALT = 0x2D,
    CRYING_LARGE_MARIO_1 = 0x2E,
    CRYING_LARGE_MARIO_2 = 0x2F,
    JUMPING_SMALL_MARIO_1 = 0x30,
    JUMPING_SMALL_MARIO_2 = 0x31,
    CRYING_SMALL_MARIO_1 = 0x32,
    CRYING_SMALL_MARIO_2 = 0x33,
    ROCKET_SMOKE_1 = 0x34,
    ROCKET_SMOKE_2 = 0x35,
    JUMPING_LARGE_LUIGI_1 = 0x36,
    JUMPING_LARGE_LUIGI_2 = 0x37,
    ALTERNATIVE_EXHAUST_1 = 0x38,
    ALTERNATIVE_EXHAUST_2 = 0x39,
    CRYING_LARGE_LUIGI_1 = 0x3A,
    CRYING_LARGE_LUIGI_2 = 0x3B,
    JUMPING_SMALL_LUIGI_1 = 0x3C,
    JUMPING_SMALL_LUIGI_2 = 0x3D,
    CRYING_SMALL_LUIGI_1 = 0x3E,
    CRYING_SMALL_LUIGI_2 = 0x3F,
    BURAN_EXHAUST_1 = 0x40,
    BURAN_EXHAUST_2 = 0x41,
    CRYING_SMALL_LUIGI_2_ALT = 0x42,
    VIOLINIST_1_ALT = 0x43,

    // Ending-dance musicians.
    VIOLINIST_1 = 0x44,
    VIOLINIST_2 = 0x45,
    CELLIST_1 = 0x46,
    CELLIST_2 = 0x47,
    BIG_DRUM_1 = 0x48,
    BIG_DRUM_2 = 0x49,
    GUITARIST_1 = 0x4A,
    GUITARIST_2 = 0x4B,
    FLUTIST_PAIR_1 = 0x4C,
    FLUTIST_PAIR_2 = 0x4D,
    BAYAN_1 = 0x4E,
    BAYAN_2 = 0x4F,
    JUMPING_COSSACK_1 = 0x50,
    JUMPING_COSSACK_2 = 0x51,
    DANCER_1 = 0x52,
    DANCER_2 = 0x53,
    KOKOSHNIK_WOMAN_1 = 0x54,
    KOKOSHNIK_WOMAN_2 = 0x55,

    // Victory-crash smoke and the score-ranked rockets with exhaust.
    VICTORY_CRASH_SMOKE_SMALL = 0x56,
    VICTORY_CRASH_SMOKE_LARGE = 0x57,
    ROCKET_L = 0x58,
    ROCKET_M = 0x59,
    ROCKET_S = 0x5A,
    ROCKET_S_ALT = 0x5B,
    ROCKET_EXHAUST_1 = 0x5C,
    ROCKET_EXHAUST_2 = 0x5D,
};

}  // namespace kirpich
