#pragma once
// GENERATED by tools/asm_parser/parse_core_enums.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.

// The authoritative value sets for the two label/dispatch-encoded core enums, scanned from source.
// The hand-authored headers (include/kirpich/game_state.h, serial_state.h) carry port-design
// *names*; this fixture guards their *values*. tests/test_core_enums.cpp drift-checks the two.

#include <array>
#include <cstdint>
#include <string_view>

namespace kirpich::fixtures {

struct GameStateRow {
    std::uint8_t     value;
    std::string_view label;    // upstream GameState_XX label (structural anchor)
    std::string_view comment;  // upstream jump-table comment (informational)
};

// 54 states, contiguous 0x00..0x35. The 0x36 slot upstream is a raw `dw $27EA` over-read and is
// deliberately absent here - it is not a state.
inline constexpr std::array<GameStateRow, 54> kGameStateExpected{{
    {0x00, "GameState_00", "Normal gameplay"},
    {0x01, "GameState_01", "Init game over"},
    {0x02, "GameState_02", "Buran liftoff"},
    {0x03, "GameState_03", "Buran rising"},
    {0x04, "GameState_04", "Game over screen"},
    {0x05, "GameState_05", "Type B victory jingle"},
    {0x06, "GameState_06", "Init title screen"},
    {0x07, "GameState_07", "Title screen"},
    {0x08, "GameState_08", "Init Game Type/Music Type Selection Screen"},
    {0x09, "GameState_09", "just points to a random RET... what?"},
    {0x0A, "GameState_0A", "Init game?"},
    {0x0B, "GameState_0B", "Init Type B scoreboard"},
    {0x0C, "GameState_0C", "?"},
    {0x0D, "GameState_0D", "Game over curtain"},
    {0x0E, "GameState_0E", "Select Game Type"},
    {0x0F, "GameState_0F", "Select Music Type"},
    {0x10, "GameState_10", "Init Type A difficulty selection"},
    {0x11, "GameState_11", "Type A level selection"},
    {0x12, "GameState_12", "Init Type B difficulty selection"},
    {0x13, "GameState_13", "Type B level selection"},
    {0x14, "GameState_14", "Type B start height selection"},
    {0x15, "GameState_15", "Entering topscore for either game type"},
    {0x16, "GameState_16", "Init 2P game difficulty selection"},
    {0x17, "GameState_17", "Select 2P game start height"},
    {0x18, "GameState_18", "Init 2P game"},
    {0x19, "GameState_19", "Init 2P game (2x)"},
    {0x1A, "GameState_1A", "2P game"},
    {0x1B, "GameState_1B", "2P end of game jingle?"},
    {0x1C, "GameState_1C", "Prepare garbage?"},
    {0x1D, "GameState_1D", "Init 2P victory screen?"},
    {0x1E, "GameState_1E", "Init 2P defeat screen?"},
    {0x1F, "GameState_1F", "Init 2P game (3x)"},
    {0x20, "GameState_20", "2P victory screen"},
    {0x21, "GameState_21", "2P defeat screen"},
    {0x22, "GameState_22", "Init Type B bonus ending"},
    {0x23, "GameState_23", "Dancers"},
    {0x24, "GameState_24", "Init copyright screen"},
    {0x25, "GameState_25", "Copyright screen"},
    {0x26, "GameState_26", "Init Buran"},
    {0x27, "GameState_27", "Prepare Buran launch"},
    {0x28, "GameState_28", "Buran ignition"},
    {0x29, "GameState_29", "Buran ignition for real this time"},
    {0x2A, "GameState_2A", "Init 2P music selection?"},
    {0x2B, "GameState_2B", "2P Select music"},
    {0x2C, "GameState_2C", "Print congratulations"},
    {0x2D, "GameState_2D", "Congratulations"},
    {0x2E, "GameState_2E", "Init rocket launch"},
    {0x2F, "GameState_2F", "Rocket"},
    {0x30, "GameState_30", "Rocket ignition"},
    {0x31, "GameState_31", "Rocket liftoff"},
    {0x32, "GameState_32", "Rocket main engine fire"},
    {0x33, "GameState_33", "End of bonus scene"},
    {0x34, "GameState_34", "Game over screen leading to bonus ending"},
    {0x35, "GameState_35", "Copyright screen, but skippable"},
}};

struct SerialStateRow {
    std::uint8_t     index;
    std::string_view label;
};

// Reachable serial states only: dispatch indices 0..3 (index 4 upstream is a vestigial bare ret).
inline constexpr std::array<SerialStateRow, 4> kSerialStateExpected{{
    {0x00, "Handshake"},
    {0x01, "SerialState_01"},
    {0x02, "SerialState_02"},
    {0x03, "SerialState_03"},
}};

}  // namespace kirpich::fixtures
