#pragma once
// GENERATED by tools/asm_parser/parse_garbage.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus demo-garbage sweep: the 40 bytes of TypeBDemoGarbage
// in serialization order (row-major), flat and independent of the composed grid in src/data/garbage.h
// so a defect in the header cannot mask the sweep. tests/test_garbage.cpp asserts the composed grid
// equals these bytes cell for cell.

#include <array>
#include <cstdint>

namespace kirpich::fixtures {

inline constexpr std::array<std::uint8_t, 40> kExpectedTypeBDemoGarbageBytes = {{
    0x85, 0x2F, 0x82, 0x86, 0x83, 0x2F, 0x2F, 0x80, 0x82, 0x85,
    0x2F, 0x82, 0x84, 0x82, 0x83, 0x2F, 0x83, 0x2F, 0x87, 0x2F,
    0x2F, 0x85, 0x2F, 0x83, 0x2F, 0x86, 0x82, 0x80, 0x81, 0x2F,
    0x83, 0x2F, 0x86, 0x83, 0x2F, 0x85, 0x2F, 0x85, 0x2F, 0x2F,
}};

}  // namespace kirpich::fixtures
