#pragma once
// GENERATED by tools/asm_parser/parse_gravity.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus gravity sweep: the 21 ROM bytes as plain
// integers, indexed by level. Deliberately holds no port type, so a defect in src/data/gravity.h
// cannot mask the sweep in tests/test_gravity.cpp.

#include <array>
#include <cstdint>

namespace kirpich::fixtures {

inline constexpr std::array<std::uint8_t, 21> kExpectedFramesPerDrop{{
    52, 48, 44, 40, 36, 32, 27,  // levels 0-6
    21, 16, 10,  9,  8,  7,  6,  // levels 7-13
     5,  5,  4,  4,  3,  3,  2,  // levels 14-20
}};

}  // namespace kirpich::fixtures
