#pragma once
// GENERATED by tools/asm_parser/parse_hram.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// The HRAM layout contract and the raw-operand census, both derived from the upstream disassembly.
//
// kHramLabels: every label in tetris/hram.asm and every anonymous region between labels, each as
// {name, address, size} with a kind tag. Addresses derive from the $FF80 section origin and the
// reservations that precede each label - nothing here is hand-typed. A Field owns its reservation;
// an Alias shares an earlier field's address (hTempPreviewPiece aliases hTopScorePointerLo at
// $FFFC); a Gap is anonymous padding or the bare slot left by a commented-out label. Regions tile
// $FF80..$FFFD exactly (the walk ends at $FFFE, one below rIE).
//
// kHramCensus: {address, refCount} for every STATIC raw-operand HRAM access in tetris/tetris.asm -
// numeric `ldh` operands and 16-bit pointer loads of an HRAM address. Symbolic `ldh [hLabel]`
// accesses are not counted (the label is already visible in kHramLabels). The census makes the
// bytes reached only through a raw operand - the gaps and commented-out slots - provable owners of
// some state unit. Sorted by address.
//
// Totals: 60 fields, 1 alias, 19 gaps, 1 section; 57 census addresses.

#include <array>
#include <cstdint>
#include <string_view>

namespace kirpich::fixtures {

enum class HramKind : std::uint8_t { Field, Alias, Gap };

// One region of the HRAM map. `size` is bytes reserved; for an Alias it repeats the field's size.
struct HramLabel {
    std::string_view name;      // "" for a Gap
    std::uint16_t    address;
    std::uint16_t    size;
    HramKind         kind;
};

// The HRAM section: [origin, end) tiled exactly by its regions [first, first + count).
struct HramSection {
    std::string_view name;
    std::uint16_t    origin;
    std::uint16_t    end;       // one past the last byte
    std::uint16_t    first;     // index of the first region in kHramLabels
    std::uint16_t    count;     // number of regions in this section
};

// One raw-operand HRAM address and how many static access sites reach it.
struct HramCensus {
    std::uint16_t address;
    std::uint16_t refCount;
};

inline constexpr std::array<HramLabel, 80> kHramLabels{{
    { .name = "hJoyHeld", .address = 0xFF80, .size = 1, .kind = HramKind::Field },
    { .name = "hJoyPressed", .address = 0xFF81, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFF82, .size = 3, .kind = HramKind::Gap },  // gap
    { .name = "hVBlankInterruptTriggered", .address = 0xFF85, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFF86, .size = 7, .kind = HramKind::Gap },  // gap
    { .name = "hSpriteRendererOAMHi", .address = 0xFF8D, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererOAMLo", .address = 0xFF8E, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererCount", .address = 0xFF8F, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererOffsetY", .address = 0xFF90, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererOffsetX", .address = 0xFF91, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererObjX", .address = 0xFF92, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererObjY", .address = 0xFF93, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFF94, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hSpriteRendererVisible", .address = 0xFF95, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererSpriteHi", .address = 0xFF96, .size = 1, .kind = HramKind::Field },
    { .name = "hSpriteRendererSpriteLo", .address = 0xFF97, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFF98, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hDropTimer", .address = 0xFF99, .size = 1, .kind = HramKind::Field },
    { .name = "hFramesPerDrop", .address = 0xFF9A, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFF9B, .size = 3, .kind = HramKind::Gap },  // gap
    { .name = "hLines", .address = 0xFF9E, .size = 2, .kind = HramKind::Field },
    { .name = "", .address = 0xFFA0, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hSavedIE", .address = 0xFFA1, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFA2, .size = 4, .kind = HramKind::Gap },  // gap
    { .name = "hTimer1", .address = 0xFFA6, .size = 1, .kind = HramKind::Field },
    { .name = "hTimer2", .address = 0xFFA7, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFA8, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hLevel", .address = 0xFFA9, .size = 1, .kind = HramKind::Field },
    { .name = "hKeyRepeatTimer", .address = 0xFFAA, .size = 1, .kind = HramKind::Field },
    { .name = "hPaused", .address = 0xFFAB, .size = 1, .kind = HramKind::Field },
    { .name = "hMarioStartHeight", .address = 0xFFAC, .size = 1, .kind = HramKind::Field },
    { .name = "hLuigiStartHeight", .address = 0xFFAD, .size = 1, .kind = HramKind::Field },
    { .name = "hNextPreviewPiece", .address = 0xFFAE, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFAF, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hNumPiecesPlayed", .address = 0xFFB0, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFB1, .size = 5, .kind = HramKind::Gap },  // gap
    { .name = "hDMARoutine", .address = 0xFFB6, .size = 10, .kind = HramKind::Field },
    { .name = "hGameType", .address = 0xFFC0, .size = 1, .kind = HramKind::Field },
    { .name = "hMusicType", .address = 0xFFC1, .size = 1, .kind = HramKind::Field },
    { .name = "hTypeALevel", .address = 0xFFC2, .size = 1, .kind = HramKind::Field },
    { .name = "hTypeBLevel", .address = 0xFFC3, .size = 1, .kind = HramKind::Field },
    { .name = "hTypeBStartHeight", .address = 0xFFC4, .size = 1, .kind = HramKind::Field },
    { .name = "hIsMultiplayer", .address = 0xFFC5, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFC6, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hNewTopScore", .address = 0xFFC7, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFC8, .size = 3, .kind = HramKind::Gap },  // gap
    { .name = "hSerialRole", .address = 0xFFCB, .size = 1, .kind = HramKind::Field },
    { .name = "hSerialInterruptTriggered", .address = 0xFFCC, .size = 1, .kind = HramKind::Field },
    { .name = "hSerialState", .address = 0xFFCD, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFCE, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hSerialTx", .address = 0xFFCF, .size = 1, .kind = HramKind::Field },
    { .name = "hSerialRx", .address = 0xFFD0, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFD1, .size = 6, .kind = HramKind::Gap },  // gap
    { .name = "hOurWins", .address = 0xFFD7, .size = 1, .kind = HramKind::Field },
    { .name = "hTheirWins", .address = 0xFFD8, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFD9, .size = 8, .kind = HramKind::Gap },  // gap
    { .name = "hGameState", .address = 0xFFE1, .size = 1, .kind = HramKind::Field },
    { .name = "hFrameCounter", .address = 0xFFE2, .size = 1, .kind = HramKind::Field },
    { .name = "hWipeCounter", .address = 0xFFE3, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoNumber", .address = 0xFFE4, .size = 1, .kind = HramKind::Field },
    { .name = "hSoftDropCounter", .address = 0xFFE5, .size = 1, .kind = HramKind::Field },
    { .name = "hLevelTilemapPointerLo", .address = 0xFFE6, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFE7, .size = 1, .kind = HramKind::Gap },  // gap
    { .name = "hRedrawTopScoresDuringVBlank", .address = 0xFFE8, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoRecording", .address = 0xFFE9, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoJoypadTimer", .address = 0xFFEA, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoJoypadDataHi", .address = 0xFFEB, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoJoypadDataLo", .address = 0xFFEC, .size = 1, .kind = HramKind::Field },
    { .name = "hDemoJoypadHeld", .address = 0xFFED, .size = 1, .kind = HramKind::Field },
    { .name = "hSavedJoyHeld", .address = 0xFFEE, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFEF, .size = 2, .kind = HramKind::Gap },  // gap
    { .name = "hSavedSerialTx", .address = 0xFFF1, .size = 1, .kind = HramKind::Field },
    { .name = "hSavedSerialRx", .address = 0xFFF2, .size = 1, .kind = HramKind::Field },
    { .name = "hRocketSpriteIndex", .address = 0xFFF3, .size = 1, .kind = HramKind::Field },
    { .name = "hHeartMode", .address = 0xFFF4, .size = 1, .kind = HramKind::Field },
    { .name = "", .address = 0xFFF5, .size = 6, .kind = HramKind::Gap },  // gap
    { .name = "hTopScorePointerHi", .address = 0xFFFB, .size = 1, .kind = HramKind::Field },
    { .name = "hTopScorePointerLo", .address = 0xFFFC, .size = 1, .kind = HramKind::Field },
    { .name = "hTempPreviewPiece", .address = 0xFFFC, .size = 1, .kind = HramKind::Alias },  // alias
    { .name = "", .address = 0xFFFD, .size = 1, .kind = HramKind::Gap },  // gap
}};

inline constexpr std::array<HramSection, 1> kHramSections{{
    { .name = "HRAM", .origin = 0xFF80, .end = 0xFFFE, .first = 0, .count = 80 },
}};

inline constexpr std::array<HramCensus, 57> kHramCensus{{
    { .address = 0xFF86, .refCount = 1 },
    { .address = 0xFF87, .refCount = 1 },
    { .address = 0xFF88, .refCount = 1 },
    { .address = 0xFF89, .refCount = 3 },
    { .address = 0xFF8A, .refCount = 1 },
    { .address = 0xFF8B, .refCount = 3 },
    { .address = 0xFF8C, .refCount = 2 },
    { .address = 0xFF94, .refCount = 3 },
    { .address = 0xFF98, .refCount = 14 },
    { .address = 0xFF9B, .refCount = 5 },
    { .address = 0xFF9C, .refCount = 12 },
    { .address = 0xFF9E, .refCount = 2 },
    { .address = 0xFF9F, .refCount = 5 },
    { .address = 0xFFA0, .refCount = 22 },
    { .address = 0xFFA4, .refCount = 1 },
    { .address = 0xFFA6, .refCount = 1 },
    { .address = 0xFFA9, .refCount = 1 },
    { .address = 0xFFAC, .refCount = 1 },
    { .address = 0xFFAD, .refCount = 1 },
    { .address = 0xFFAF, .refCount = 1 },
    { .address = 0xFFB0, .refCount = 2 },
    { .address = 0xFFB1, .refCount = 5 },
    { .address = 0xFFB2, .refCount = 4 },
    { .address = 0xFFB3, .refCount = 4 },
    { .address = 0xFFB4, .refCount = 3 },
    { .address = 0xFFB5, .refCount = 2 },
    { .address = 0xFFC0, .refCount = 1 },
    { .address = 0xFFC1, .refCount = 1 },
    { .address = 0xFFC2, .refCount = 2 },
    { .address = 0xFFC3, .refCount = 2 },
    { .address = 0xFFC4, .refCount = 1 },
    { .address = 0xFFC6, .refCount = 17 },
    { .address = 0xFFC8, .refCount = 2 },
    { .address = 0xFFC9, .refCount = 6 },
    { .address = 0xFFCA, .refCount = 7 },
    { .address = 0xFFCE, .refCount = 15 },
    { .address = 0xFFD1, .refCount = 9 },
    { .address = 0xFFD2, .refCount = 6 },
    { .address = 0xFFD3, .refCount = 8 },
    { .address = 0xFFD4, .refCount = 7 },
    { .address = 0xFFD5, .refCount = 4 },
    { .address = 0xFFD6, .refCount = 4 },
    { .address = 0xFFD7, .refCount = 1 },
    { .address = 0xFFD8, .refCount = 1 },
    { .address = 0xFFD9, .refCount = 5 },
    { .address = 0xFFDA, .refCount = 5 },
    { .address = 0xFFDB, .refCount = 5 },
    { .address = 0xFFDC, .refCount = 6 },
    { .address = 0xFFE0, .refCount = 10 },
    { .address = 0xFFE2, .refCount = 1 },
    { .address = 0xFFE4, .refCount = 1 },
    { .address = 0xFFE5, .refCount = 2 },
    { .address = 0xFFED, .refCount = 1 },
    { .address = 0xFFEF, .refCount = 8 },
    { .address = 0xFFF0, .refCount = 3 },
    { .address = 0xFFFB, .refCount = 1 },
    { .address = 0xFFFE, .refCount = 1 },
}};

}  // namespace kirpich::fixtures
