#pragma once
// GENERATED by tools/asm_parser/parse_music.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus music sweep. Holds the song/channel/section address graph,
// the per-section {addr, length, SHA-1} pins (NOT the note bytes - those are hashed from the ROM at
// test time and never committed), the StereoData rows, and the note-length region. Deliberately
// carries its own record types so a defect in src/data/music.h cannot mask the sweep.

#include <array>
#include <cstdint>
#include <string_view>

namespace kirpich::fixtures {

struct MusicSongExpected {
    std::uint8_t                 id;               // wire MusicId ($01..$11)
    std::uint16_t                headerAddr;       // Song_ label address
    std::uint8_t                 byte0;            // header byte 0 (-> $DF80, unused)
    std::uint16_t                lengthTableAddr;  // note-length table pointer
    std::array<std::uint16_t, 4> channelAddrs;     // 0 = unused channel
    bool operator==(const MusicSongExpected&) const = default;
};

enum class MusicChannelTerm : std::uint8_t { None, Stop, Repeat };

struct MusicChannelExpected {
    std::uint16_t    addr;
    MusicChannelTerm terminator;
    std::uint16_t    repeatTargetAddr;  // valid iff terminator == Repeat
    std::uint16_t    sectionCount;
    std::uint16_t    poolOffset;        // into kMusicChannelSectionPool
    bool operator==(const MusicChannelExpected&) const = default;
};

struct MusicSectionExpected {
    std::uint16_t    addr;
    std::uint16_t    length;
    std::string_view sha1;  // SHA-1 of the section's ROM bytes, lower-case hex
    bool operator==(const MusicSectionExpected&) const = default;
};

inline constexpr std::array<MusicSongExpected, 17> kExpectedMusicSongs{{
    { .id = 0x01, .headerAddr = 0x6F3F, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7CF9, 0x7CFF, 0x7D11, 0x7D21 }} },
    { .id = 0x02, .headerAddr = 0x6F4A, .byte0 = 0x00, .lengthTableAddr = 0x6F05, .channelAddrs = {{ 0x7E48, 0x7E44, 0x7E4A, 0x7E4C }} },
    { .id = 0x03, .headerAddr = 0x6F55, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x763B, 0x7633, 0x7641, 0x7663 }} },
    { .id = 0x04, .headerAddr = 0x6F60, .byte0 = 0x00, .lengthTableAddr = 0x6EF9, .channelAddrs = {{ 0x7600, 0x75FC, 0x7602, 0x0000 }} },
    { .id = 0x05, .headerAddr = 0x6F6B, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x714C, 0x7142, 0x7156, 0x7162 }} },
    { .id = 0x06, .headerAddr = 0x6F76, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x72C6, 0x72B8, 0x72D4, 0x7302 }} },
    { .id = 0x07, .headerAddr = 0x6F81, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7008, 0x6FFA, 0x0000, 0x0000 }} },
    { .id = 0x08, .headerAddr = 0x6F8C, .byte0 = 0x00, .lengthTableAddr = 0x6F05, .channelAddrs = {{ 0x7E9D, 0x7E91, 0x7EA9, 0x7EB5 }} },
    { .id = 0x09, .headerAddr = 0x6F97, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7C28, 0x7C24, 0x7C2A, 0x7C2C }} },
    { .id = 0x0A, .headerAddr = 0x6FA2, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x0000, 0x7A00, 0x0000, 0x0000 }} },
    { .id = 0x0B, .headerAddr = 0x6FAD, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x0000, 0x7A26, 0x7A2A, 0x0000 }} },
    { .id = 0x0C, .headerAddr = 0x6FB8, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7A73, 0x7A6F, 0x7A75, 0x0000 }} },
    { .id = 0x0D, .headerAddr = 0x6FC3, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7ADF, 0x7AE3, 0x7AE5, 0x7AE7 }} },
    { .id = 0x0E, .headerAddr = 0x6FCE, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x7B65, 0x7B6B, 0x7B6F, 0x7B73 }} },
    { .id = 0x0F, .headerAddr = 0x6FD9, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x786C, 0x7876, 0x787E, 0x7886 }} },
    { .id = 0x10, .headerAddr = 0x6FE4, .byte0 = 0x00, .lengthTableAddr = 0x6F2B, .channelAddrs = {{ 0x7543, 0x754B, 0x7551, 0x0000 }} },
    { .id = 0x11, .headerAddr = 0x6FEF, .byte0 = 0x00, .lengthTableAddr = 0x6F0E, .channelAddrs = {{ 0x758D, 0x7595, 0x759B, 0x0000 }} },
}};

inline constexpr std::array<std::uint16_t, 164> kMusicChannelSectionPool{{
    0x7016, 0x7034, 0x7016, 0x704D, 0x7093, 0x7062, 0x7074, 0x7062,
    0x7085, 0x70F4, 0x7168, 0x7168, 0x71AE, 0x71CB, 0x71CB, 0x721D,
    0x723A, 0x723A, 0x727F, 0x727F, 0x72A3, 0x730B, 0x733F, 0x7367,
    0x7367, 0x73C9, 0x7308, 0x733C, 0x738E, 0x738E, 0x744B, 0x731F,
    0x7353, 0x73B5, 0x73B5, 0x73B5, 0x73B5, 0x73B5, 0x73B5, 0x74C0,
    0x74DE, 0x74DE, 0x74DE, 0x74EE, 0x74FE, 0x74FE, 0x750E, 0x750E,
    0x751E, 0x751E, 0x750E, 0x752E, 0x7333, 0x7557, 0x7562, 0x755E,
    0x757C, 0x75A1, 0x75AC, 0x75A8, 0x75EE, 0x7604, 0x7614, 0x7623,
    0x766F, 0x7769, 0x7769, 0x76BF, 0x77AA, 0x783C, 0x770C, 0x77EB,
    0x77EB, 0x77F5, 0x77EB, 0x77EB, 0x77FE, 0x77F5, 0x77EB, 0x77EB,
    0x77FE, 0x77F5, 0x7807, 0x7811, 0x77FE, 0x77F5, 0x77EB, 0x775B,
    0x775B, 0x781A, 0x781A, 0x781A, 0x781A, 0x788E, 0x7911, 0x788E,
    0x7996, 0x78AD, 0x7938, 0x78AD, 0x79BA, 0x78D5, 0x795E, 0x78D5,
    0x79DD, 0x78FE, 0x7984, 0x78FE, 0x7984, 0x7A04, 0x7A2C, 0x7A4B,
    0x7A77, 0x7A96, 0x7AB4, 0x7AE9, 0x7B08, 0x7B25, 0x7B4F, 0x7B77,
    0x7BCE, 0x7B96, 0x7BF2, 0x7BA8, 0x7C02, 0x7BBB, 0x7C12, 0x7C2E,
    0x7C63, 0x7C97, 0x7CCB, 0x7D2E, 0x7D29, 0x7D35, 0x7D5B, 0x7D82,
    0x7D5B, 0x7DA4, 0x7DC6, 0x7D3B, 0x7D6C, 0x7D93, 0x7D6C, 0x7DB5,
    0x7E07, 0x7D3E, 0x7D41, 0x7E4E, 0x7E5E, 0x7E6D, 0x7E7D, 0x7EBB,
    0x7F28, 0x7EBB, 0x7F73, 0x7EE5, 0x7F4F, 0x7EE5, 0x7F96, 0x7EFB,
    0x7F61, 0x7EFB, 0x7FAE, 0x7F11,
}};

inline constexpr std::array<MusicChannelExpected, 57> kExpectedMusicChannels{{
    { .addr = 0x6FFA, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x6FFA, .sectionCount = 5, .poolOffset = 0 },
    { .addr = 0x7008, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7008, .sectionCount = 5, .poolOffset = 5 },
    { .addr = 0x7142, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7142, .sectionCount = 3, .poolOffset = 10 },
    { .addr = 0x714C, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x714C, .sectionCount = 3, .poolOffset = 13 },
    { .addr = 0x7156, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7156, .sectionCount = 4, .poolOffset = 16 },
    { .addr = 0x7162, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7162, .sectionCount = 1, .poolOffset = 20 },
    { .addr = 0x72B8, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x72B8, .sectionCount = 5, .poolOffset = 21 },
    { .addr = 0x72C6, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x72C6, .sectionCount = 5, .poolOffset = 26 },
    { .addr = 0x72D4, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x72D4, .sectionCount = 21, .poolOffset = 31 },
    { .addr = 0x7302, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7302, .sectionCount = 1, .poolOffset = 52 },
    { .addr = 0x7543, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7545, .sectionCount = 2, .poolOffset = 53 },
    { .addr = 0x754B, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x754B, .sectionCount = 1, .poolOffset = 55 },
    { .addr = 0x7551, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7551, .sectionCount = 1, .poolOffset = 56 },
    { .addr = 0x758D, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x758F, .sectionCount = 2, .poolOffset = 57 },
    { .addr = 0x7595, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7595, .sectionCount = 1, .poolOffset = 59 },
    { .addr = 0x759B, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x759B, .sectionCount = 1, .poolOffset = 60 },
    { .addr = 0x75FC, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 61 },
    { .addr = 0x7600, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 62 },
    { .addr = 0x7602, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 63 },
    { .addr = 0x7633, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 3, .poolOffset = 64 },
    { .addr = 0x763B, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 3, .poolOffset = 67 },
    { .addr = 0x7641, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 17, .poolOffset = 70 },
    { .addr = 0x7663, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 6, .poolOffset = 87 },
    { .addr = 0x786C, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 4, .poolOffset = 93 },
    { .addr = 0x7876, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 4, .poolOffset = 97 },
    { .addr = 0x787E, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 4, .poolOffset = 101 },
    { .addr = 0x7886, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 4, .poolOffset = 105 },
    { .addr = 0x7A00, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 109 },
    { .addr = 0x7A26, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 110 },
    { .addr = 0x7A2A, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 111 },
    { .addr = 0x7A6F, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 112 },
    { .addr = 0x7A73, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 113 },
    { .addr = 0x7A75, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 114 },
    { .addr = 0x7ADF, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 115 },
    { .addr = 0x7AE3, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 116 },
    { .addr = 0x7AE5, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 117 },
    { .addr = 0x7AE7, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 118 },
    { .addr = 0x7B65, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 2, .poolOffset = 119 },
    { .addr = 0x7B6B, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 2, .poolOffset = 121 },
    { .addr = 0x7B6F, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 2, .poolOffset = 123 },
    { .addr = 0x7B73, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 2, .poolOffset = 125 },
    { .addr = 0x7C24, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 127 },
    { .addr = 0x7C28, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 128 },
    { .addr = 0x7C2A, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 129 },
    { .addr = 0x7C2C, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 130 },
    { .addr = 0x7CF9, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7D01, .sectionCount = 1, .poolOffset = 131 },
    { .addr = 0x7CFF, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7D03, .sectionCount = 7, .poolOffset = 132 },
    { .addr = 0x7D11, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7D13, .sectionCount = 6, .poolOffset = 139 },
    { .addr = 0x7D21, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7D23, .sectionCount = 2, .poolOffset = 145 },
    { .addr = 0x7E44, .terminator = MusicChannelTerm::Stop, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 147 },
    { .addr = 0x7E48, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 148 },
    { .addr = 0x7E4A, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 149 },
    { .addr = 0x7E4C, .terminator = MusicChannelTerm::None, .repeatTargetAddr = 0x0000, .sectionCount = 1, .poolOffset = 150 },
    { .addr = 0x7E91, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7E91, .sectionCount = 4, .poolOffset = 151 },
    { .addr = 0x7E9D, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7E9D, .sectionCount = 4, .poolOffset = 155 },
    { .addr = 0x7EA9, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7EA9, .sectionCount = 4, .poolOffset = 159 },
    { .addr = 0x7EB5, .terminator = MusicChannelTerm::Repeat, .repeatTargetAddr = 0x7EB5, .sectionCount = 1, .poolOffset = 163 },
}};

inline constexpr std::array<MusicSectionExpected, 119> kExpectedMusicSections{{
    { .addr = 0x7016, .length =  30, .sha1 = "2b2341a6b9ea746db3ac2b0c11638f4ca2139244" },
    { .addr = 0x7034, .length =  25, .sha1 = "f943eb9b8290a4a83616452e2d8a9b1e3e089583" },
    { .addr = 0x704D, .length =  21, .sha1 = "a78fdf4b4483ed2edfcca196a3614a3c90ed5b2a" },
    { .addr = 0x7062, .length =  18, .sha1 = "ab3f3d7b987e93a242e99cc7b0a7b1cd35d57597" },
    { .addr = 0x7074, .length =  17, .sha1 = "0e73417c8349fabaf3dc5de2279b9bc700de7c12" },
    { .addr = 0x7085, .length =  14, .sha1 = "d70b45d315a6c4978346c309d06aa892fae6c181" },
    { .addr = 0x7093, .length =  97, .sha1 = "0c6bbf80b85ed82f7f7ae47b0207d1e798816109" },
    { .addr = 0x70F4, .length =  78, .sha1 = "45af9dcbd93af070e9250088617b7360b3311437" },
    { .addr = 0x7168, .length =  70, .sha1 = "f0c3847799959678a3b636fb3e1fc471e830cc25" },
    { .addr = 0x71AE, .length =  29, .sha1 = "5f03df19deafbce95753cf9234505a416e5c44d0" },
    { .addr = 0x71CB, .length =  82, .sha1 = "dbf715a8241392c7a9aae886610e08252a209730" },
    { .addr = 0x721D, .length =  29, .sha1 = "b3adb68622f1ad65b6818219f36822e1872b5d3e" },
    { .addr = 0x723A, .length =  69, .sha1 = "6fbf8503bc0c3cae96d6ec430269bdde454e864e" },
    { .addr = 0x727F, .length =  36, .sha1 = "4e02ee7089937a43d32572fe6ed3273679be7e7e" },
    { .addr = 0x72A3, .length =  21, .sha1 = "12e821a5a5dae7c82f3b60bf0b8f4609601a1f54" },
    { .addr = 0x7308, .length =   3, .sha1 = "75611cdf2b8f523d16f1f36e7cd0aa69605240f7" },
    { .addr = 0x730B, .length =  20, .sha1 = "d9d64f889fff6c805e2062d10cb05ee2afcb7c2e" },
    { .addr = 0x731F, .length =  20, .sha1 = "73540fa8f89d80bff9820b55eb6d1bb5a5f3fd92" },
    { .addr = 0x7333, .length =   9, .sha1 = "b06bf0415c9863695466144d52a9a80098d4127d" },
    { .addr = 0x733C, .length =   3, .sha1 = "75611cdf2b8f523d16f1f36e7cd0aa69605240f7" },
    { .addr = 0x733F, .length =  20, .sha1 = "951dcea03cbd11891937aa3c73f7be9db04c52fe" },
    { .addr = 0x7353, .length =  20, .sha1 = "73540fa8f89d80bff9820b55eb6d1bb5a5f3fd92" },
    { .addr = 0x7367, .length =  39, .sha1 = "1dda36c214211519c4fb73bca18c38b7e6b18fab" },
    { .addr = 0x738E, .length =  39, .sha1 = "7e7d55ddd1faf946282879ec143ed86b2e3c9961" },
    { .addr = 0x73B5, .length =  20, .sha1 = "73540fa8f89d80bff9820b55eb6d1bb5a5f3fd92" },
    { .addr = 0x73C9, .length = 130, .sha1 = "bce48c861e3e367bc6ba754ef3676007f1079b51" },
    { .addr = 0x744B, .length = 117, .sha1 = "da2a0a35633fe014a84d02a6447a7535563103f2" },
    { .addr = 0x74C0, .length =  30, .sha1 = "2d8f33b9ebee3cc5e20543bde1d365bb500f285f" },
    { .addr = 0x74DE, .length =  16, .sha1 = "d96552871d814a784f70ed8647b446f6c7f5c84c" },
    { .addr = 0x74EE, .length =  16, .sha1 = "4d67b17f8d78899285f3f6aba61c2841b6233b45" },
    { .addr = 0x74FE, .length =  16, .sha1 = "f91cd68f96b37cb2d31451e56069639beb4c5a4c" },
    { .addr = 0x750E, .length =  16, .sha1 = "be76641f77eb8fa3f76fb20b86aed178dadb904f" },
    { .addr = 0x751E, .length =  16, .sha1 = "db4f42605d6ed0086bfc9d8cc12ebee9fe8e222f" },
    { .addr = 0x752E, .length =  21, .sha1 = "e65bb4c7041f075f1f0d778059404d8eb0e095c2" },
    { .addr = 0x7557, .length =   7, .sha1 = "569563c8105415bf2ebb1386dd2822e2d8f2e91e" },
    { .addr = 0x755E, .length =   4, .sha1 = "4ac09e745d6315f64f8ebbb3b80ab488acf67921" },
    { .addr = 0x7562, .length =  26, .sha1 = "3918fad7aa1c10c6c21db0a6dc8a2b0ad2ce93a5" },
    { .addr = 0x757C, .length =  17, .sha1 = "15217df36e9d6526a466d79c77da6482d906990c" },
    { .addr = 0x75A1, .length =   7, .sha1 = "569563c8105415bf2ebb1386dd2822e2d8f2e91e" },
    { .addr = 0x75A8, .length =   4, .sha1 = "4ac09e745d6315f64f8ebbb3b80ab488acf67921" },
    { .addr = 0x75AC, .length =  66, .sha1 = "ea3be3cd2bff56f8b7ac4a60ed74e2823c4baf97" },
    { .addr = 0x75EE, .length =  14, .sha1 = "dfbabd92479e28819ce173dc90c96965558c020c" },
    { .addr = 0x7604, .length =  16, .sha1 = "3f5799903ec5d8d45782d890fcba70fcadd181bb" },
    { .addr = 0x7614, .length =  15, .sha1 = "32b05e3b5d8bbbd912f318ab8229a2620b823a89" },
    { .addr = 0x7623, .length =  16, .sha1 = "690ac8cceed7b96cefd80f6a3d5eab37e45fca74" },
    { .addr = 0x766F, .length =  80, .sha1 = "f3d7ebb3b724adadc5ab8e52f50548b50bfd7e37" },
    { .addr = 0x76BF, .length =  77, .sha1 = "38582cd0ceca74db12d019fa86f983ba8124fcce" },
    { .addr = 0x770C, .length =  79, .sha1 = "d60a94d0dd3195b3cc6cda7608507335a1ecff43" },
    { .addr = 0x775B, .length =  14, .sha1 = "bbd8087733d15b4060bf2d7851c10f3a81720b7c" },
    { .addr = 0x7769, .length =  65, .sha1 = "8a7c2e1d18a693bab3fe689aab60f3e17a5095f3" },
    { .addr = 0x77AA, .length =  65, .sha1 = "1aae4b9ee3e10626769e9f12da339981779b8d91" },
    { .addr = 0x77EB, .length =  10, .sha1 = "648781bb37097d6754fc500f39407a897b22e6c2" },
    { .addr = 0x77F5, .length =   9, .sha1 = "842b2ddc5185f39abd8580b90ce29dbb1437705b" },
    { .addr = 0x77FE, .length =   9, .sha1 = "b2523c0128629d919d54f983ca33bcd73697ac4a" },
    { .addr = 0x7807, .length =  10, .sha1 = "9e619c0af6df44e38a73ac1ba19423b969e436c1" },
    { .addr = 0x7811, .length =   9, .sha1 = "aff6ceb39fd302badb5cff129b8535c0809396ee" },
    { .addr = 0x781A, .length =  34, .sha1 = "0aa888c8dbc03799def08a9d515cac19adc58db6" },
    { .addr = 0x783C, .length =  48, .sha1 = "d25550990a1ef9b07fc31de132169225c752fecb" },
    { .addr = 0x788E, .length =  31, .sha1 = "eabdc8dddefeeb30fcb7ac63d06a77fb8c0d292c" },
    { .addr = 0x78AD, .length =  40, .sha1 = "13539552e91b8ab4b2489fcb1f42807733f68397" },
    { .addr = 0x78D5, .length =  41, .sha1 = "5eb7983be47210b6e0af6449cefba74032ba58fd" },
    { .addr = 0x78FE, .length =  19, .sha1 = "1fd85cbd82a264556770b16f4286d5fb147d2b4e" },
    { .addr = 0x7911, .length =  39, .sha1 = "408cafdf6faad6d0f5f944ba1c376d97b70d4195" },
    { .addr = 0x7938, .length =  38, .sha1 = "27dba03caa231d9811f40f9e52328bffc64d3659" },
    { .addr = 0x795E, .length =  38, .sha1 = "2dbf258360adab8dfa684fe88b99f44dfdfcdb0e" },
    { .addr = 0x7984, .length =  18, .sha1 = "8277233c4796a30bea65f2b23a31e685d9ca8894" },
    { .addr = 0x7996, .length =  36, .sha1 = "e02bf48586d68e4dc237890cf321265457f8341b" },
    { .addr = 0x79BA, .length =  35, .sha1 = "61250bf353dbb48364bc13b4d3041f12c57d2876" },
    { .addr = 0x79DD, .length =  35, .sha1 = "0e0b0ca8dc74d32d3163f86db3a37d687e54beb2" },
    { .addr = 0x7A04, .length =  34, .sha1 = "fd6f44d58f63aec7353ce81491627cfd6cd6f1c1" },
    { .addr = 0x7A2C, .length =  31, .sha1 = "dc86b6d10bfca0b2c945990b14dfccde281a14dc" },
    { .addr = 0x7A4B, .length =  36, .sha1 = "29187c7a164421ce882d21af67df576afb5f91c5" },
    { .addr = 0x7A77, .length =  31, .sha1 = "dc86b6d10bfca0b2c945990b14dfccde281a14dc" },
    { .addr = 0x7A96, .length =  30, .sha1 = "16d541037582d658fac6e20f8ac46eecb0eb885e" },
    { .addr = 0x7AB4, .length =  43, .sha1 = "68aa71bfc710836ed36b22cd749b19e32e1cf23e" },
    { .addr = 0x7AE9, .length =  31, .sha1 = "dc86b6d10bfca0b2c945990b14dfccde281a14dc" },
    { .addr = 0x7B08, .length =  29, .sha1 = "1bcc267104902d8e5642b00c3bdb3a314992a336" },
    { .addr = 0x7B25, .length =  42, .sha1 = "fd72170d9810dd6ef64739e3e310cddf0dba98d8" },
    { .addr = 0x7B4F, .length =  22, .sha1 = "49d4e2faebff6e9ed24525a01ed559c3aa46a348" },
    { .addr = 0x7B77, .length =  31, .sha1 = "eabdc8dddefeeb30fcb7ac63d06a77fb8c0d292c" },
    { .addr = 0x7B96, .length =  18, .sha1 = "5a5690f9a8fdd351ca353b12665a33a8a71cd1a2" },
    { .addr = 0x7BA8, .length =  19, .sha1 = "86fd5f55d14a6399c2840fd8a4e818f0baab32e0" },
    { .addr = 0x7BBB, .length =  19, .sha1 = "1fd85cbd82a264556770b16f4286d5fb147d2b4e" },
    { .addr = 0x7BCE, .length =  36, .sha1 = "9adfba911bc86e729045d07761c23394fd97d59d" },
    { .addr = 0x7BF2, .length =  16, .sha1 = "309f0ab3f01f94543ec0f6ae4e0e2cd93189a658" },
    { .addr = 0x7C02, .length =  16, .sha1 = "4a18688827d1bcce3c0288ef100e2fb46c5af4a8" },
    { .addr = 0x7C12, .length =  18, .sha1 = "ea218f35a8d2aa5e416b17d4802d8cd6ef2f04a2" },
    { .addr = 0x7C2E, .length =  53, .sha1 = "36aba557fdb2d16068b0faa4d7f94be0993a42eb" },
    { .addr = 0x7C63, .length =  52, .sha1 = "ece0bd08628a1afa264e48ce1142e59b2e382604" },
    { .addr = 0x7C97, .length =  52, .sha1 = "22ee3ba04b7d3dec5467b6788d6272eb3ebf3827" },
    { .addr = 0x7CCB, .length =  46, .sha1 = "cc3f09b646cef0f80cdbb934377f3d7b070b65a2" },
    { .addr = 0x7D29, .length =   5, .sha1 = "0f81130602a419b7048aa607af71aa729d96ffe3" },
    { .addr = 0x7D2E, .length =   7, .sha1 = "569563c8105415bf2ebb1386dd2822e2d8f2e91e" },
    { .addr = 0x7D35, .length =   6, .sha1 = "a2a3364370d9b98fca0ba8db6b5bbc7407ab4100" },
    { .addr = 0x7D3B, .length =   3, .sha1 = "75611cdf2b8f523d16f1f36e7cd0aa69605240f7" },
    { .addr = 0x7D3E, .length =   3, .sha1 = "75611cdf2b8f523d16f1f36e7cd0aa69605240f7" },
    { .addr = 0x7D41, .length =  26, .sha1 = "4c3f3be6dcd45728bdd162801af791ec79012529" },
    { .addr = 0x7D5B, .length =  17, .sha1 = "955e641cc640cee54bbbcbbed3be9bcdcf431983" },
    { .addr = 0x7D6C, .length =  22, .sha1 = "64ebe0d9d73f1fc7a2fe9e6df6421cdde46be61a" },
    { .addr = 0x7D82, .length =  17, .sha1 = "9115b4bcee08442f8556412797e3fd704d46d24b" },
    { .addr = 0x7D93, .length =  17, .sha1 = "ec5d5dc33f6dfce571c7dbabd622f9591e185f3f" },
    { .addr = 0x7DA4, .length =  17, .sha1 = "8b0773d378427b59de921c2b2723795f6e58e8c3" },
    { .addr = 0x7DB5, .length =  17, .sha1 = "ec5d5dc33f6dfce571c7dbabd622f9591e185f3f" },
    { .addr = 0x7DC6, .length =  65, .sha1 = "c2634acf5f6bb78f611113d279af874147529298" },
    { .addr = 0x7E07, .length =  61, .sha1 = "6b3b602ac9719c9523e78cc17b414bc1019c4bed" },
    { .addr = 0x7E4E, .length =  16, .sha1 = "77a91db73f20a36114de9f6ed6ffa087b7e56d9a" },
    { .addr = 0x7E5E, .length =  15, .sha1 = "38287c1aaa04eadb23326114c8fd4a05ca79dbdf" },
    { .addr = 0x7E6D, .length =  16, .sha1 = "8747c11458cc9e11831ce4da0680dddc0414711c" },
    { .addr = 0x7E7D, .length =  20, .sha1 = "6f8466904527d28584f4ec3932dde689db42d2d4" },
    { .addr = 0x7EBB, .length =  42, .sha1 = "2ca34bbb47c78e7814b342ecf6938daf8b6b0ae6" },
    { .addr = 0x7EE5, .length =  22, .sha1 = "e06577488dff05b7f458bad9982f0546f589a576" },
    { .addr = 0x7EFB, .length =  22, .sha1 = "b23d9efaee7fd5bdee1b0438aa399f2d0ecd78d5" },
    { .addr = 0x7F11, .length =  23, .sha1 = "bcc7736e39e7a75b5aeea9b3149f949d3e29c9fb" },
    { .addr = 0x7F28, .length =  39, .sha1 = "d44fe6c211cef91d1b0ce15e618776a54038a401" },
    { .addr = 0x7F4F, .length =  18, .sha1 = "0df90d8a83c53d073588de7b620f3fce677f4a7d" },
    { .addr = 0x7F61, .length =  18, .sha1 = "27ff1d7c4746482d48fc0a43949e117fdda0028b" },
    { .addr = 0x7F73, .length =  35, .sha1 = "950842125b45c8d56486790671177fbaaff19b24" },
    { .addr = 0x7F96, .length =  24, .sha1 = "a31afff6873854b65db65c55eb46753ee36d4d3f" },
    { .addr = 0x7FAE, .length =  24, .sha1 = "f89cb58024cb79d6a001fceddd61e4fd2603ff87" },
}};

inline constexpr std::array<std::array<std::uint8_t, 4>, 17>
    kExpectedStereoData{{
    {{0x01, 0x24, 0xEF, 0x56}},  // song 1
    {{0x01, 0x00, 0xE5, 0x00}},  // song 2
    {{0x01, 0x20, 0xFD, 0x00}},  // song 3
    {{0x01, 0x20, 0xDE, 0xF7}},  // song 4
    {{0x03, 0x18, 0x7F, 0xF7}},  // song 5
    {{0x03, 0x18, 0xF7, 0x7F}},  // song 6
    {{0x03, 0x48, 0xDF, 0x5B}},  // song 7
    {{0x01, 0x18, 0xDB, 0xE7}},  // song 8
    {{0x01, 0x00, 0xFD, 0xF7}},  // song 9
    {{0x03, 0x20, 0x7F, 0xF7}},  // song 10
    {{0x01, 0x20, 0xED, 0xF7}},  // song 11
    {{0x01, 0x20, 0xED, 0xF7}},  // song 12
    {{0x01, 0x20, 0xED, 0xF7}},  // song 13
    {{0x01, 0x20, 0xED, 0xF7}},  // song 14
    {{0x01, 0x20, 0xED, 0xF7}},  // song 15
    {{0x01, 0x20, 0xEF, 0xF7}},  // song 16
    {{0x01, 0x20, 0xEF, 0xF7}},  // song 17
}};

inline constexpr std::array<std::uint8_t, 70> kExpectedNoteLengthRegion{{
    0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x0C, 0x18, 0x30, 0x05, 0x00, 0x01,
    0x03, 0x05, 0x0A, 0x14, 0x28, 0x50, 0x0F, 0x1E, 0x3C, 0x03, 0x06, 0x0C,
    0x18, 0x30, 0x60, 0x12, 0x24, 0x48, 0x08, 0x10, 0x00, 0x07, 0x0E, 0x1C,
    0x38, 0x70, 0x15, 0x2A, 0x54, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x18,
    0x30, 0x60, 0x04, 0x09, 0x12, 0x24, 0x48, 0x90, 0x1B, 0x36, 0x6C, 0x0C,
    0x18, 0x04, 0x0A, 0x14, 0x28, 0x50, 0xA0, 0x1E, 0x3C, 0x78,
}};

}  // namespace kirpich::fixtures
