#pragma once
// GENERATED by tools/asm_parser/parse_playing_field.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus playing-field wipe sweep: the 18 address triples
// (counter, VRAM destination, WRAM source) exactly as the original's wipe routines hold them. It
// keeps the raw ROM serialization - addresses the port itself does not use - so the closed-form
// checks in tests/test_playing_field.cpp verify the geometry against source values, not against the
// port's own re-derivation of them.

#include <array>
#include <cstdint>

namespace kirpich::fixtures {

// One wipe routine's data: the counter value that fires it, and the DMG addresses it copies a
// 10-byte field row between (BG-map destination <- shadow-field source).
struct PlayingFieldWipeExpectedRow {
    std::uint8_t  counter;  // hWipeCounter value that triggers this row copy
    std::uint16_t vram;     // BG-map destination address in the original
    std::uint16_t wram;     // shadow-field source address in the original
};

inline constexpr std::array<PlayingFieldWipeExpectedRow, 18> kExpectedPlayingFieldWipes{{
    { .counter =  2, .vram = 0x9A22, .wram = 0xCA22 },
    { .counter =  3, .vram = 0x9A02, .wram = 0xCA02 },
    { .counter =  4, .vram = 0x99E2, .wram = 0xC9E2 },
    { .counter =  5, .vram = 0x99C2, .wram = 0xC9C2 },
    { .counter =  6, .vram = 0x99A2, .wram = 0xC9A2 },
    { .counter =  7, .vram = 0x9982, .wram = 0xC982 },
    { .counter =  8, .vram = 0x9962, .wram = 0xC962 },
    { .counter =  9, .vram = 0x9942, .wram = 0xC942 },
    { .counter = 10, .vram = 0x9922, .wram = 0xC922 },
    { .counter = 11, .vram = 0x9902, .wram = 0xC902 },
    { .counter = 12, .vram = 0x98E2, .wram = 0xC8E2 },
    { .counter = 13, .vram = 0x98C2, .wram = 0xC8C2 },
    { .counter = 14, .vram = 0x98A2, .wram = 0xC8A2 },
    { .counter = 15, .vram = 0x9882, .wram = 0xC882 },
    { .counter = 16, .vram = 0x9862, .wram = 0xC862 },
    { .counter = 17, .vram = 0x9842, .wram = 0xC842 },
    { .counter = 18, .vram = 0x9822, .wram = 0xC822 },
    { .counter = 19, .vram = 0x9802, .wram = 0xC802 },
}};

}  // namespace kirpich::fixtures
