#pragma once
// GENERATED by tools/asm_parser/parse_scoring.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus scoring sweeps: the ROM's wire bytes as plain
// integers - the BCD score immediates, the threshold/sprite ladder, and the single-site
// constant bytes. Deliberately holds no port type, so a defect in src/data/scoring.h cannot
// mask the sweeps in tests/test_scoring.cpp.

#include <array>
#include <cstdint>

namespace kirpich::fixtures {

// The four 16-bit BCD score immediates, in kind order (Single, Double, Triple, Tetris).
inline constexpr std::array<std::uint16_t, 4> kExpectedLineClearScoreBcd{{
    0x0040, 0x0100, 0x0300, 0x1200,
}};

// The bonus-ending ladder in ROM check order: the top-score-byte thresholds and the rocket
// sprite byte each tier selects.
inline constexpr std::array<std::uint8_t, 3> kExpectedBonusThresholdBcd{{
    0x20, 0x15, 0x10,
}};
inline constexpr std::array<std::uint8_t, 3> kExpectedRocketSprites{{
    0x58, 0x59, 0x5A,
}};

// Single-site constant bytes, as the ROM spells them.
inline constexpr std::uint8_t  kExpectedLevelCapByte = 0x14;      // plain binary
inline constexpr std::uint8_t  kExpectedTypeBLineGoalBcd = 0x25;  // BCD
inline constexpr std::uint16_t kExpectedSoftDropOperand = 0x0001;
inline constexpr std::uint8_t  kExpectedSaturationByte = 0x99;      // BCD, stored thrice

}  // namespace kirpich::fixtures
