#pragma once
// GENERATED by tools/asm_parser/parse_sprite_grids.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus sprite-grid sweep. Mirrors the five grids the engine
// header holds, in its own arrays, so a defect in src/data/sprite_grids.h cannot mask the sweep.
// tests/test_sprite_grids.cpp asserts the engine arrays equal these element-for-element.

#include <array>

#include "data/sprite_grids.h"

namespace kirpich::fixtures {

// kExpectedSpriteGrid4x4 - Matrix_31A9 (4x4).
inline constexpr std::array<SpriteGridOffset, 16> kExpectedSpriteGrid4x4{{
    { .y = 0x00, .x = 0x00 },
    { .y = 0x00, .x = 0x08 },
    { .y = 0x00, .x = 0x10 },
    { .y = 0x00, .x = 0x18 },
    { .y = 0x08, .x = 0x00 },
    { .y = 0x08, .x = 0x08 },
    { .y = 0x08, .x = 0x10 },
    { .y = 0x08, .x = 0x18 },
    { .y = 0x10, .x = 0x00 },
    { .y = 0x10, .x = 0x08 },
    { .y = 0x10, .x = 0x10 },
    { .y = 0x10, .x = 0x18 },
    { .y = 0x18, .x = 0x00 },
    { .y = 0x18, .x = 0x08 },
    { .y = 0x18, .x = 0x10 },
    { .y = 0x18, .x = 0x18 },
}};

// kExpectedSpriteGrid1x8 - Matrix_31C9 (1x8).
inline constexpr std::array<SpriteGridOffset, 8> kExpectedSpriteGrid1x8{{
    { .y = 0x00, .x = 0x00 },
    { .y = 0x00, .x = 0x08 },
    { .y = 0x00, .x = 0x10 },
    { .y = 0x00, .x = 0x18 },
    { .y = 0x00, .x = 0x20 },
    { .y = 0x00, .x = 0x28 },
    { .y = 0x00, .x = 0x30 },
    { .y = 0x00, .x = 0x38 },
}};

// kExpectedSpriteGrid7x2 - Matrix_31D9 (7x2).
inline constexpr std::array<SpriteGridOffset, 14> kExpectedSpriteGrid7x2{{
    { .y = 0x00, .x = 0x00 },
    { .y = 0x00, .x = 0x08 },
    { .y = 0x08, .x = 0x00 },
    { .y = 0x08, .x = 0x08 },
    { .y = 0x10, .x = 0x00 },
    { .y = 0x10, .x = 0x08 },
    { .y = 0x18, .x = 0x00 },
    { .y = 0x18, .x = 0x08 },
    { .y = 0x20, .x = 0x00 },
    { .y = 0x20, .x = 0x08 },
    { .y = 0x28, .x = 0x00 },
    { .y = 0x28, .x = 0x08 },
    { .y = 0x30, .x = 0x00 },
    { .y = 0x30, .x = 0x08 },
}};

// kExpectedSpriteGrid8x4Notched - Matrix_31F5 (8x4Notched).
inline constexpr std::array<SpriteGridOffset, 28> kExpectedSpriteGrid8x4Notched{{
    { .y = 0x00, .x = 0x08 },
    { .y = 0x00, .x = 0x10 },
    { .y = 0x08, .x = 0x08 },
    { .y = 0x08, .x = 0x10 },
    { .y = 0x10, .x = 0x00 },
    { .y = 0x10, .x = 0x08 },
    { .y = 0x10, .x = 0x10 },
    { .y = 0x10, .x = 0x18 },
    { .y = 0x18, .x = 0x00 },
    { .y = 0x18, .x = 0x08 },
    { .y = 0x18, .x = 0x10 },
    { .y = 0x18, .x = 0x18 },
    { .y = 0x20, .x = 0x00 },
    { .y = 0x20, .x = 0x08 },
    { .y = 0x20, .x = 0x10 },
    { .y = 0x20, .x = 0x18 },
    { .y = 0x28, .x = 0x00 },
    { .y = 0x28, .x = 0x08 },
    { .y = 0x28, .x = 0x10 },
    { .y = 0x28, .x = 0x18 },
    { .y = 0x30, .x = 0x00 },
    { .y = 0x30, .x = 0x08 },
    { .y = 0x30, .x = 0x10 },
    { .y = 0x30, .x = 0x18 },
    { .y = 0x38, .x = 0x00 },
    { .y = 0x38, .x = 0x08 },
    { .y = 0x38, .x = 0x10 },
    { .y = 0x38, .x = 0x18 },
}};

// kExpectedSpriteGrid3x3 - Matrix_322D (3x3).
inline constexpr std::array<SpriteGridOffset, 9> kExpectedSpriteGrid3x3{{
    { .y = 0x00, .x = 0x00 },
    { .y = 0x00, .x = 0x08 },
    { .y = 0x00, .x = 0x10 },
    { .y = 0x08, .x = 0x00 },
    { .y = 0x08, .x = 0x08 },
    { .y = 0x08, .x = 0x10 },
    { .y = 0x10, .x = 0x00 },
    { .y = 0x10, .x = 0x08 },
    { .y = 0x10, .x = 0x10 },
}};
}  // namespace kirpich::fixtures
