#pragma once
// GENERATED by tools/asm_parser/parse_tile_graphics.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Independent fixture for the full-corpus tile-graphics sweep: the 4 extraction rows plus,
// per block, its decoded PNG dimensions and the FNV-1a-64 hash of its decoded index content. The
// pixels themselves are ROM-derived and never committed - the hash is what the C++ test recomputes
// from the engine-decoded indices to prove the decode. Independent of the typed surface it guards.

#include <array>
#include <cstdint>

namespace kirpich::fixtures {

// One graphics block's expected facts: its extraction row, the greyscale PNG's dimensions and bit
// depth, and the FNV-1a-64 hash over its decoded index content (row-major, one byte per pixel).
struct TileGraphicExpected {
    const char*   fileName;     // bare file name written under assets/gfx/default/
    std::uint16_t romOffset;    // first byte of the block in the ROM
    std::uint16_t tileCount;    // number of 8x8 tiles in the block
    std::uint8_t  bitDepth;     // 1 (font) or 2; the PNG's greyscale bit depth
    int           pngWidth;     // decoded width in pixels (always 128 - 16 tiles across)
    int           pngHeight;    // decoded height in pixels (ceil(tileCount / 16) * 8)
    std::uint64_t contentHash;  // FNV-1a-64 of the decoded index content
};

inline constexpr std::array<TileGraphicExpected, 4> kExpectedTileGraphics{{
    { .fileName = "font.png", .romOffset = 0x415F, .tileCount = 39, .bitDepth = 1, .pngWidth = 128, .pngHeight = 24, .contentHash = 0x51D6F661A8AC6628ULL },
    { .fileName = "copyrightandtitlescreen.png", .romOffset = 0x4297, .tileCount = 119, .bitDepth = 2, .pngWidth = 128, .pngHeight = 64, .contentHash = 0xCF7AD4A16BC554E2ULL },
    { .fileName = "configandgameplay.png", .romOffset = 0x323F, .tileCount = 197, .bitDepth = 2, .pngWidth = 128, .pngHeight = 104, .contentHash = 0x6F83343F7E79F09FULL },
    { .fileName = "multiplayerandburan.png", .romOffset = 0x55AC, .tileCount = 207, .bitDepth = 2, .pngWidth = 128, .pngHeight = 104, .contentHash = 0x77DDB807AF83F4A3ULL },
}};

}  // namespace kirpich::fixtures
