#pragma once
// GENERATED by tools/asm_parser/parse_wram.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// The WRAM layout contract: every label in tetris/wram.asm and every anonymous gap between labels,
// each as {name, address, size} with a kind tag. Addresses derive from the section origins and the
// reservations that precede each label - nothing here is hand-typed. Fields own their reservation;
// an Alias shares an earlier field's address (wLineClearStats aliases wSinglesCount); a Gap is
// anonymous padding or an address jump. Regions tile each section with no overlap and no hole.
//
// The $C000 gameplay rows are pinned against the EngineState struct widths; the top-scores and
// Audio-RAM rows are carried for the state types that reuse this layout.
//
// Totals: 36 fields, 1 alias, 14 gaps, 2 sections.

#include <array>
#include <cstdint>
#include <string_view>

namespace kirpich::fixtures {

enum class WramKind : std::uint8_t { Field, Alias, Gap };

// One region of the WRAM map. `size` is bytes reserved; for an Alias it repeats the field's size.
struct WramLabel {
    std::string_view name;      // "" for a Gap
    std::uint16_t    address;
    std::uint16_t    size;
    WramKind         kind;
};

// A WRAM0 section: [origin, end) tiled exactly by its regions [first, first + count).
struct WramSection {
    std::string_view name;
    std::uint16_t    origin;
    std::uint16_t    end;       // one past the last byte
    std::uint16_t    first;     // index of the first region in kWramLabels
    std::uint16_t    count;     // number of regions in this section
};

inline constexpr std::array<WramLabel, 51> kWramLabels{{
    { .name = "wOAMBuffer", .address = 0xC000, .size = 160, .kind = WramKind::Field },
    { .name = "wScore", .address = 0xC0A0, .size = 3, .kind = WramKind::Field },
    { .name = "wLineClearsList", .address = 0xC0A3, .size = 9, .kind = WramKind::Field },
    { .name = "wLineClearStats", .address = 0xC0AC, .size = 1, .kind = WramKind::Field },
    { .name = "wSinglesCount", .address = 0xC0AC, .size = 1, .kind = WramKind::Alias },  // alias
    { .name = "", .address = 0xC0AD, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wDoublesCount", .address = 0xC0B1, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xC0B2, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wTriplesCount", .address = 0xC0B6, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xC0B7, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wTetrisCount", .address = 0xC0BB, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xC0BC, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wSoftDropPoints", .address = 0xC0C0, .size = 2, .kind = WramKind::Field },
    { .name = "wSoftDropPointsBCD", .address = 0xC0C2, .size = 3, .kind = WramKind::Field },
    { .name = "wScoreboardState", .address = 0xC0C5, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xC0C6, .size = 24, .kind = WramKind::Gap },  // gap
    { .name = "wHidePreviewPiece", .address = 0xC0DE, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xC0DF, .size = 545, .kind = WramKind::Gap },  // gap
    { .name = "wPieceList", .address = 0xC300, .size = 256, .kind = WramKind::Field },
    { .name = "", .address = 0xC400, .size = 3072, .kind = WramKind::Gap },  // gap
    { .name = "wTypeBTopScores", .address = 0xD000, .size = 1620, .kind = WramKind::Field },
    { .name = "wTypeATopScores", .address = 0xD654, .size = 270, .kind = WramKind::Field },
    { .name = "", .address = 0xD762, .size = 2062, .kind = WramKind::Gap },  // gap
    { .name = "wMusicCurrentChannel", .address = 0xDF70, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDF71, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wPanFrameCounter", .address = 0xDF75, .size = 1, .kind = WramKind::Field },
    { .name = "wPanInterval", .address = 0xDF76, .size = 1, .kind = WramKind::Field },
    { .name = "wPanCounter", .address = 0xDF77, .size = 1, .kind = WramKind::Field },
    { .name = "wMonoOrStereo", .address = 0xDF78, .size = 1, .kind = WramKind::Field },
    { .name = "wChannelEnableMask1", .address = 0xDF79, .size = 1, .kind = WramKind::Field },
    { .name = "wChannelEnableMask2", .address = 0xDF7A, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDF7B, .size = 3, .kind = WramKind::Gap },  // gap
    { .name = "wPauseTuneTimer", .address = 0xDF7E, .size = 1, .kind = WramKind::Field },
    { .name = "wPauseUnpauseSound", .address = 0xDF7F, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDF80, .size = 96, .kind = WramKind::Gap },  // gap
    { .name = "wNewSquareSFXID", .address = 0xDFE0, .size = 1, .kind = WramKind::Field },
    { .name = "wCurrentSquareSFXID", .address = 0xDFE1, .size = 1, .kind = WramKind::Field },
    { .name = "wSquareSFXCounter", .address = 0xDFE2, .size = 1, .kind = WramKind::Field },
    { .name = "wSquareSFXNoteLength", .address = 0xDFE3, .size = 1, .kind = WramKind::Field },
    { .name = "wSquareSFXNoteCounter", .address = 0xDFE4, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDFE5, .size = 3, .kind = WramKind::Gap },  // gap
    { .name = "wNewMusicID", .address = 0xDFE8, .size = 1, .kind = WramKind::Field },
    { .name = "wCurrentMusicID", .address = 0xDFE9, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDFEA, .size = 6, .kind = WramKind::Gap },  // gap
    { .name = "wNewWaveSFXID", .address = 0xDFF0, .size = 1, .kind = WramKind::Field },
    { .name = "wCurrentWaveSFXID", .address = 0xDFF1, .size = 1, .kind = WramKind::Field },
    { .name = "wWaveSFXCounter", .address = 0xDFF2, .size = 1, .kind = WramKind::Field },
    { .name = "wWaveSFXNoteLength", .address = 0xDFF3, .size = 1, .kind = WramKind::Field },
    { .name = "", .address = 0xDFF4, .size = 4, .kind = WramKind::Gap },  // gap
    { .name = "wNewNoiseSFXID", .address = 0xDFF8, .size = 1, .kind = WramKind::Field },
    { .name = "wCurrentNoiseSFXID", .address = 0xDFF9, .size = 1, .kind = WramKind::Field },
}};

inline constexpr std::array<WramSection, 2> kWramSections{{
    { .name = "WRAM", .origin = 0xC000, .end = 0xDF70, .first = 0, .count = 23 },
    { .name = "Audio RAM", .origin = 0xDF70, .end = 0xDFFA, .first = 23, .count = 28 },
}};

}  // namespace kirpich::fixtures
