#pragma once
// GENERATED by tools/asm_parser/parse_demo.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// Demo data: the two attract-mode joypad recordings and the piece sequence they share.
//
// The game plays two attract-mode demos by running the normal game loop with recorded input in place
// of the player's. Each demo is a run-length-encoded timeline - a list of DemoInputRecords, one per
// input change - and both demos draw their pieces from a single fixed list rather than the RNG.
//
//   - kTypeADemoInputs / kTypeBDemoInputs: the Type A and Type B timelines. Each record is the set of
//     game actions held (held, a retropp::ActionSet over kirpich::Action) and the number of frames it
//     persists before the next record loads (frames). The recordings capture Game Boy joypad state; the
//     port resolves those button bits to the actions the gameplay input handler binds them to, so a
//     record holds actions, not a hardware byte, ready for the demo-replay system to feed into the
//     engine input path. Deriving the pressed edge from the held set is runtime behavior and ports with
//     the input system. The streams do not self-terminate - the demo ends by piece count, so trailing
//     records are simply never reached.
//   - kDemoPieceList: the deterministic piece sequence both demos replay. Each entry is a $C200
//     piece-spec value (kind * 4 + rotation, rotation always 0 = spawn orientation), the same Piece
//     wrapper the piece logic uses. The Type A demo consumes indices 0-15 and the Type B demo 17-29;
//     index 16 is never read (see docs/contracts/demo.md).
//
// This unit is the data only. Feeding the records into the input path, selecting between the two demos,
// and ending a demo by piece count are the demo state machine's job and port with the gameplay logic;
// docs/contracts/demo.md specifies that behavior with source line anchors.
//
// Generated from the disassembly by tools/asm_parser/parse_demo.py; edit the source and regenerate,
// not here.

#include <array>
#include <cstdint>
#include <initializer_list>

#include <retropp/input.h>

#include <kirpich/action.h>
#include <kirpich/piece.h>

namespace kirpich {

// The engine action set held during one demo step, built from named actions.
[[nodiscard]] constexpr retropp::ActionSet heldActions(std::initializer_list<Action> actions) {
    retropp::ActionSet set;
    for (const Action action : actions) {
        set.set(retropp::actionId(action), true);
    }
    return set;
}

// One run-length-encoded step of a demo: the actions held, and how many frames they hold.
struct DemoInputRecord {
    retropp::ActionSet held;    // the game actions held this step (empty = no input)
    std::uint8_t       frames;  // frames the state persists before the next record loads

    friend constexpr bool operator==(const DemoInputRecord&, const DemoInputRecord&) = default;
};

// Number of records in each timeline, and the length of the shared piece list.
inline constexpr std::uint16_t kTypeADemoInputCount = 128;
inline constexpr std::uint16_t kTypeBDemoInputCount = 80;
inline constexpr std::uint16_t kDemoPieceCount      = 48;

// The Type A demo's action timeline (128 records).
inline constexpr std::array<DemoInputRecord, kTypeADemoInputCount> kTypeADemoInputs = {{
    { .held = heldActions({}), .frames = 0x2A },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x01 },
    { .held = heldActions({}), .frames = 0x1D },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x09 },
    { .held = heldActions({}), .frames = 0x07 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x0B },
    { .held = heldActions({}), .frames = 0x03 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x20 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x17 },
    { .held = heldActions({}), .frames = 0x06 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x1E },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x0B },
    { .held = heldActions({}), .frames = 0x06 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x1C },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::MoveRight}), .frames = 0x08 },
    { .held = heldActions({Action::MoveRight, Action::RotateClockwise}), .frames = 0x04 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x02 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x1A },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x24 },
    { .held = heldActions({}), .frames = 0x15 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x20 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x0D },
    { .held = heldActions({Action::MoveRight}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x03 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x25 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x15 },
    { .held = heldActions({}), .frames = 0x1B },
    { .held = heldActions({Action::MoveRight}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x13 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x1C },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x19 },
    { .held = heldActions({}), .frames = 0x1A },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x01 },
    { .held = heldActions({}), .frames = 0x09 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x02 },
    { .held = heldActions({}), .frames = 0x14 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x0E },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x16 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::MoveRight}), .frames = 0x0A },
    { .held = heldActions({Action::MoveRight, Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x16 },
    { .held = heldActions({}), .frames = 0x13 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x25 },
    { .held = heldActions({}), .frames = 0x1C },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x03 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x02 },
    { .held = heldActions({}), .frames = 0x0E },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x02 },
    { .held = heldActions({}), .frames = 0x03 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x0D },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x21 },
    { .held = heldActions({}), .frames = 0x13 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x06 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x02 },
    { .held = heldActions({}), .frames = 0x1C },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x0E },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x12 },
    { .held = heldActions({}), .frames = 0x0C },
    { .held = heldActions({Action::MoveRight}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x02 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x08 },
    { .held = heldActions({}), .frames = 0x10 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x08 },
    { .held = heldActions({}), .frames = 0x1E },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x19 },
    { .held = heldActions({}), .frames = 0x10 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x24 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x1C },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x11 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x12 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x20 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::MoveRight}), .frames = 0x01 },
    { .held = heldActions({Action::MoveRight, Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x03 },
    { .held = heldActions({}), .frames = 0x02 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x19 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
}};

// The Type B demo's action timeline (80 records).
inline constexpr std::array<DemoInputRecord, kTypeBDemoInputCount> kTypeBDemoInputs = {{
    { .held = heldActions({}), .frames = 0x4D },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x08 },
    { .held = heldActions({Action::MoveLeft, Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x0B },
    { .held = heldActions({}), .frames = 0x07 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x64 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x00 },
    { .held = heldActions({Action::MoveRight, Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x2F },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x16 },
    { .held = heldActions({}), .frames = 0x17 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x06 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x10 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x18 },
    { .held = heldActions({}), .frames = 0x34 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x01 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x0E },
    { .held = heldActions({Action::MoveRight, Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x20 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x0A },
    { .held = heldActions({}), .frames = 0x2B },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x06 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x05 },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::MoveLeft}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x0C },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x02 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x0B },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x04 },
    { .held = heldActions({}), .frames = 0x0D },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x1C },
    { .held = heldActions({}), .frames = 0x75 },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x0E },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x1F },
    { .held = heldActions({}), .frames = 0x1A },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x06 },
    { .held = heldActions({}), .frames = 0x04 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x08 },
    { .held = heldActions({}), .frames = 0x03 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x08 },
    { .held = heldActions({}), .frames = 0x0C },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x0F },
    { .held = heldActions({}), .frames = 0x0A },
    { .held = heldActions({Action::RotateClockwise}), .frames = 0x07 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({Action::MoveRight}), .frames = 0x3D },
    { .held = heldActions({}), .frames = 0x05 },
    { .held = heldActions({Action::SoftDrop}), .frames = 0x1F },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
    { .held = heldActions({}), .frames = 0x00 },
}};

// The deterministic piece sequence both demos replay (48 pieces, spawn orientation).
inline constexpr std::array<Piece, kDemoPieceCount> kDemoPieceList = {{
    Piece{0x10}, Piece{0x18}, Piece{0x00}, Piece{0x04}, Piece{0x08}, Piece{0x00}, Piece{0x04}, Piece{0x08}, Piece{0x08}, Piece{0x00}, Piece{0x04}, Piece{0x14},
    Piece{0x10}, Piece{0x08}, Piece{0x10}, Piece{0x10}, Piece{0x14}, Piece{0x18}, Piece{0x14}, Piece{0x00}, Piece{0x0C}, Piece{0x04}, Piece{0x18}, Piece{0x00},
    Piece{0x14}, Piece{0x14}, Piece{0x08}, Piece{0x04}, Piece{0x04}, Piece{0x0C}, Piece{0x00}, Piece{0x18}, Piece{0x04}, Piece{0x00}, Piece{0x08}, Piece{0x0C},
    Piece{0x0C}, Piece{0x18}, Piece{0x00}, Piece{0x0C}, Piece{0x08}, Piece{0x00}, Piece{0x18}, Piece{0x10}, Piece{0x14}, Piece{0x14}, Piece{0x18}, Piece{0x08},
}};

}  // namespace kirpich
