#pragma once
// GENERATED by tools/asm_parser/parse_music.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// MusicId + the music-data address map. The song sequences themselves are never committed: the
// engine-hosted sound driver reads the driver's ROM image at these absolute addresses, so the port
// carries only the identifiers the game writes to wNewMusicID and the spans that locate the data.
// Section content is verified by hashing the ROM at test time (see tests/test_music.cpp).

#include <cstdint>

namespace kirpich {

// The byte the game writes to wNewMusicID. StartMusic special-cases $00 (no-op) and $FF (stop);
// the 17 songs are $01..$11, and `value & kMusicIdIndexMask` is the 1-based MusicPointers index.
enum class MusicId : std::uint8_t {
    NONE                = 0x00,  // no-op (StartMusic returns)
    TOP_SCORE           = 0x01,  // Top Score
    STAGE_CLEAR         = 0x02,  // Stage clear
    TITLE               = 0x03,  // Title screen
    GAME_OVER           = 0x04,  // Game over
    TYPE_A              = 0x05,  // Type A - Korobeiniki
    TYPE_B              = 0x06,  // Type B
    TYPE_C              = 0x07,  // Type C - Bach, Menuet
    DANGER              = 0x08,  // Danger - Toreadors, Carmen
    ROUND_OVER          = 0x09,  // Multiplayer round over
    TYPE_B_JINGLE_1     = 0x0A,  // Type B Jingle #1
    TYPE_B_JINGLE_2     = 0x0B,  // Type B Jingle #2
    TYPE_B_JINGLE_3     = 0x0C,  // Type B Jingle #3
    TYPE_B_JINGLE_4     = 0x0D,  // Type B Jingle #4
    TYPE_B_JINGLE_5     = 0x0E,  // Type B Jingle #5
    TYPE_B_JINGLE_6     = 0x0F,  // Type B Jingle #6
    ROCKET_LAUNCH       = 0x10,  // Rocket launch
    MULTIPLAYER_VICTORY = 0x11,  // Multiplayer victory
    STOP                = 0xFF,  // stop all audio (_StopAudio)
};

inline constexpr std::uint16_t kMusicPointersAddr    = 0x64B0;
inline constexpr std::uint8_t  kMusicSongCount       = 17;
inline constexpr std::uint8_t  kMusicIdIndexMask     = 0x1F;
inline constexpr std::uint16_t kMusicSectionBase     = 0x6F3F;
inline constexpr std::uint16_t kMusicSectionEnd      = 0x7FC6;  // exclusive
inline constexpr std::uint16_t kStereoDataAddr       = 0x6ABE;
inline constexpr std::uint16_t kNoteLengthRegionBase = 0x6EF9;
inline constexpr std::uint16_t kNoteLengthRegionEnd  = 0x6F3F;  // exclusive

}  // namespace kirpich
