#pragma once
// GENERATED by tools/asm_parser/parse_sfx.py - do not hand-edit.
// Transcribed from the kaspermeerts/tetris disassembly (upstream @ b95c668).
// Regenerate with `--all` after any upstream repin; edits here are overwritten.
// The three SFX ID spaces + the SFX/driver data address map. Like the music data, the SFX
// sequences are driver code that rides the engine-hosted ROM image; the port carries
// only the identifiers the game writes to wNewSquareSFXID / wNewNoiseSFXID / wNewWaveSFXID and the
// constants that locate the tables. The data blobs themselves are verified in
// tests/fixtures/sfx_expected.h.

#include <cstdint>

namespace kirpich {

// wNewSquareSFXID: 1-based index into SquareSFXStartPointers; 0 is the no-op.
enum class SquareSfxId : std::uint8_t {
    NONE           = 0x00,  // no-op
    TINK           = 0x01,  // menu cursor movement
    CHANGE_SCREEN  = 0x02,  // menu change screen
    ROTATE_PIECE   = 0x03,  // rotate piece
    SHIFT_PIECE    = 0x04,  // shift piece
    GARBAGE_ATTACK = 0x05,  // garbage attack sweep
    LINE_CLEAR     = 0x06,  // line clear
    TETRIS         = 0x07,  // tetris
    LEVEL_UP       = 0x08,  // level up
};

// wNewNoiseSFXID: 1-based index into NoiseSFXStartPointers; 0 is the no-op.
enum class NoiseSfxId : std::uint8_t {
    NONE       = 0x00,  // no-op
    STACK_FALL = 0x01,  // stack settles after a line clear
    LOCK_PIECE = 0x02,  // piece locks
    IGNITION   = 0x03,  // rocket ignition
    LIFTOFF    = 0x04,  // rocket flying
};

// wNewWaveSFXID: PlayWaveSFX direct-compares these (no pointer table); 0 is the no-op.
enum class WaveSfxId : std::uint8_t {
    NONE         = 0x00,  // no-op
    TETRIS_SWEEP = 0x01,  // end-of-Tetris wave sweep
    GAME_OVER    = 0x02,  // game over
};

inline constexpr std::uint16_t kAudioSectionBase            = 0x6480;
inline constexpr std::uint16_t kSquareSfxStartPointersAddr  = 0x6480;
inline constexpr std::uint16_t kSquareSfxContinuePointersAddr = 0x6490;
inline constexpr std::uint16_t kNoiseSfxStartPointersAddr   = 0x64A0;
inline constexpr std::uint16_t kNoiseSfxContinuePointersAddr = 0x64A8;
inline constexpr std::uint8_t  kSquareSfxCount              = 8;
inline constexpr std::uint8_t  kNoiseSfxCount               = 4;
inline constexpr std::uint8_t  kWaveSfxCount                = 2;

}  // namespace kirpich
